---
name: Check

on:
  workflow_dispatch:
  pull_request:

jobs:   
  build:    
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Lint
      run: make lint
  
    - name: Build
      run: make
