name: aur-publish

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build release
        run: make release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/udev-dbus-notify

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@2.5.0
        with:
          pkgname: my-awesome-package
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
